/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfertasBRouteImport } from './routes/ofertas-B'
import { Route as OfertasBRouteImport } from './routes/ofertas-b'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasBRoute = OfertasBRouteImport.update({
  id: '/ofertas-B',
  path: '/ofertas-B',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasBRoute = OfertasBRouteImport.update({
  id: '/ofertas-b',
  path: '/ofertas-b',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ofertas-B': typeof OfertasBRoute
  '/ofertas-b': typeof OfertasBRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ofertas-B': typeof OfertasBRoute
  '/ofertas-b': typeof OfertasBRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ofertas-B': typeof OfertasBRoute
  '/ofertas-b': typeof OfertasBRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ofertas-B' | '/ofertas-b'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ofertas-B' | '/ofertas-b'
  id: '__root__' | '/' | '/ofertas-B' | '/ofertas-b'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OfertasBRoute: typeof OfertasBRoute
  OfertasBRoute: typeof OfertasBRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas-B': {
      id: '/ofertas-B'
      path: '/ofertas-B'
      fullPath: '/ofertas-B'
      preLoaderRoute: typeof OfertasBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas-b': {
      id: '/ofertas-b'
      path: '/ofertas-b'
      fullPath: '/ofertas-b'
      preLoaderRoute: typeof OfertasBRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OfertasBRoute: OfertasBRoute,
  OfertasBRoute: OfertasBRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
